services:
  postgres:
    image: postgres:16
    container_name: "postgres"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./.data:/var/lib/postgresql/data
      #- ./init_table.sql:/docker-entrypoint-initdb.d/init_table.sql:ro
